---
title: "1d Random-Grid Metropolis"
output: html_notebook
---

Helper Functions
```{r}
f <- function(w, x, u) {
  return(2*w * ((u[2] - 1/2) + round(x / (2*w) - (u[2] - 1/2))))
}

phi <- function(pi, w, x, u) {
  if (u[1] < pi(f(w, x, u)) / pi(x)) {
    return(f(w, x, u))
  }
  return(x)
}

rgm_history <- function(n, pi, w, x0, unifs = NULL) {
  if (is.null(unifs)) {
    unifs <- replicate(n, runif(2))
  }

  states <- numeric(n + 1)
  states[1] <- x0
  for (i in 1:n) {
    states[i+1] <- phi(pi, w, states[i], unifs[, i])
  }
  
  return(list(states, unifs))
}

rgm_final <- function(n, pi, w, x0, unifs = NULL) {
  return(rgm_history(n, pi, w, x0, unifs)[[1]][n + 1])
}
```

Test
```{r}
num_iterations <- 500
num_chains <- 1000

chain <- rgm_history(num_iterations, dnorm, 1, -5)[[1]]
plot(chain, type = "l", col = "blue")

simulations <- replicate(num_chains, rgm_final(num_iterations, dnorm, 1, -5))
hist(simulations, breaks = num_chains / 100, probability = TRUE)
curve(dnorm, add = TRUE)
```

Circular Coupling
```{r}
rgm1 <- rgm_history(num_iterations, dnorm, 1, -5)
xchain <- rgm1[[1]]
unif_history <- rgm1[[2]]

ychain <- rgm_history(num_iterations, dnorm, 1, xchain[num_iterations + 1], unif_history)[[1]]
xchain[num_iterations + 1] == ychain[num_iterations + 1]

plot(xchain, type = "l", col = "red")
lines(ychain, col = "blue")
```

Auxiliary Chains
```{r}
num_aux <- 5
num_head <- 0:(num_aux-1) * num_iterations / num_aux
num_tail <- num_iterations - num_head

plot(ychain, type = "l", col = "blue", ylim = c(-5.5, 2.5))

for (i in 1:num_aux) {
  aux_unif_history <- tail(unif_history, c(2, num_tail[i]))
  aux <- rgm_history(num_tail[i], dnorm, 1, rnorm(1, -5), aux_unif_history)[[1]]
  lines(num_head[i]:num_iterations + 1, aux, col = "red", pch = 4)
  
  #aux_unif_history <- cbind(tail(unif_history, c(2, num_tail[i])), head(unif_history, c(2, num_head[i])))
  #aux <- rgm_history(num_iterations, dnorm, 1, rnorm(1, -5), aux_unif_history)[[1]]
  #aux_reorder <- c(tail(aux, num_tail[i]), head(aux, num_head[i]))
  #lines(aux_reorder, col = "red", pch = 4)
}

lines(ychain, col = "blue")

#auxiliary0 <- rgm_history(num_iterations, dnorm, 1, rnorm(1, -5), unif_history)[[1]]
#if (sum(auxiliary0 == ychain) > 0) {
#  tau0 <- min(which(auxiliary0 == ychain))
#  lines(auxiliary0[1:tau0], col = "red", pch = 4)
#}

```

Multivariate Helper Functions
```{r}
f_multi <- function(w, x, u) {
  uis <- tail(u, length(x))
  return(2*w * ((uis - 1/2) + round(x / (2*w) - (uis - 1/2))))
}

phi_multi <- function(pi, w, x, u) {
  if (u[1] < pi(f(w, x, u)) / pi(x)) {
    return(f_multi(w, x, u))
  }
  return(x)
}

rgm_history_multi <- function(n, pi, w, x0, unifs = NULL) {
  if (is.null(unifs)) {
    unifs <- replicate(n, runif(length(x0) + 1))
  }

  states <- replicate(n + 1, numeric(length(x0)))
  states[, 1] <- x0
  for (i in 1:n) {
    states[, i+1] <- phi_multi(pi, w, states[, i], unifs[, i])
  }
  
  return(list(states, unifs))
}

rgm_final_multi <- function(n, pi, w, x0, unifs = NULL) {
  return(rgm_history_multi(n, pi, w, x0, unifs)[[1]][, n + 1])
}
```

